/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interrupciones;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnToine
 */
public class procesar extends javax.swing.JFrame {
int contador, nproceso, rafaga=0, cantidad=0, residuorafaga=0, tproceso=0, valorbarra, cantidadproceso;
    /**
     * Creates new form banderas
     */
    public procesar() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnp = new javax.swing.JLabel();
        lblproc = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpr = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnstart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblcp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbltp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interrupciones");
        jLabel1.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Gungsuh", 1, 12)); // NOI18N
        jLabel5.setText("Proceso");

        lblnp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblnp.setForeground(new java.awt.Color(255, 0, 0));
        lblnp.setToolTipText("Numero de proceso");
        lblnp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 255)));

        lblproc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblproc.setForeground(new java.awt.Color(255, 0, 0));
        lblproc.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 255)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio de procesos"));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel3.setText("Prioridad");

        btnadd.setText("Agregar");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnstart.setText("Iniciar");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gungsuh", 1, 12)); // NOI18N
        jLabel4.setText("Lista de Procesos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Proceso", "Prioridad", "Cantidad", "Residuo Prioridad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd)
                    .addComponent(btnstart))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fin de procesos"));

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad Proceso");

        lblcp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblcp.setForeground(new java.awt.Color(255, 0, 0));
        lblcp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 255)));

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel10.setText("Tiempo Procesos");

        lbltp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbltp.setForeground(new java.awt.Color(255, 0, 0));
        lbltp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Gungsuh", 1, 12)); // NOI18N
        jLabel8.setText("Historico de procesos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Proceso", "Prioridad", "Cantidad", "Tiempo final", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(219, 219, 219))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblcp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblnp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblproc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblproc, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
if((Integer.parseInt(txtpr.getText()))<=100){
        ingresar();
        txtcant.setEditable(false);
    }
else{
JOptionPane.showMessageDialog(null, "La prioridad no pueden ser mayores de 100");
txtpr.setText(null);
txtpr.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed
    }
        private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
       new Thread(new Hilo()).start();
       iniciar();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnstartActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public void ingresar(){//ingresa proceso a la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        contador++;
        Object[] mitabla= new Object[5];
        mitabla[0]=contador;
        mitabla[1]=txtpr.getText();
        mitabla[2]=txtcant.getText();
        mitabla[3]=txtpr.getText();
        mitabla[4]="listo";
        modelo.addRow(mitabla);
        jTable1.setModel (modelo);
        txtpr.setText(null);
        txtpr.grabFocus();
        
    }
    private class Hilo implements Runnable{
        @Override
        public void run(){
            int estado=1;//estado del while que indica si se puede seguir o no
                    int i=0;//contador while
                    
                    while(estado!=0){//recorre filas
                        while(i<contador){
                        cargar(i);
                        if(residuorafaga!=0 && residuorafaga>cantidad){//ejecuta procesos
                            for(int c=1; c<=cantidad;c++){
                                jTable1.setValueAt("Procesando", 1, 4);
                                residuorafaga--;
                                barra(rafaga,residuorafaga);
                                pintar();
                                jTable1.setValueAt(String.valueOf(residuorafaga),i, 3);
                                tproceso++;
                                dormir();
                            }//for
                            jTable1.setValueAt("espera", i, 4);
                            if(residuorafaga==0){
                                jTable1.setValueAt("terminado", i, 4);
                                pintar();
                                informe(i);
                                borrar(i);
                                jProgressBar1.setValue(0);
                            }
                        }else{
                                if(residuorafaga>0 && cantidad!=0){
                                    while(residuorafaga>0){
                                        jTable1.setValueAt("procesando", i, 4);
                                        residuorafaga--;
                                        barra(rafaga,residuorafaga);
                                        pintar();
                                        jTable1.setValueAt(String.valueOf(residuorafaga), i, 3);
                                        tproceso++;
                                        dormir();        
                                    }//while
                                    jTable1.setValueAt("espera", i, 4);
                                    if(residuorafaga==0 && cantidad!=0){
                                        jTable1.setValueAt("terminado", i, 4);
                                        pintar();
                                        informe(i);
                                        borrar(i);
                                        jProgressBar1.setValue(0);
                                    }//if
                                }else{
                                        if(residuorafaga==0 && cantidad!=0){
                                        jTable1.setValueAt("terminado", i, 4);
                                        pintar();
                                        informe(i);
                                        borrar(i);
                                        jProgressBar1.setValue(0);
                                    }//if
                                }//if
                            }//else
                               lblnp.setText(String.valueOf(""));
                               lblproc.setText(String.valueOf(""));
                                i++; 
                        }//if
                            i=0;
                            lblnp.setText(String.valueOf(""));
                               lblproc.setText(String.valueOf(""));
        }//while
        }//void run
    }//hilo
    public void borrar(int c){
        jTable1.setValueAt(0, c, 0);
        jTable1.setValueAt("0", c, 1);
        jTable1.setValueAt("0", c, 2);
        jTable1.setValueAt("0", c, 3);
        jTable1.setValueAt("******", c, 4);
        
    }//void borrar
    public void barra(int rafaga, int residuo){
        int Rafaga=rafaga;
        int valor=100/rafaga;
        int porcentaje=100-(valor*residuo);
        valorbarra=porcentaje;
        lblproc.setText(String.valueOf(valorbarra+"%"));
    }//void barra
        public void     pintar(){
            jProgressBar1.setValue(valorbarra);
            jProgressBar1.repaint();
        }//void pintar
        public void dormir(){
            try{
                Thread.sleep(1000);
            }catch(InterruptedException ex){
                Logger.getLogger(procesar.class.getName()).log(Level.SEVERE, null, ex);
            }//catch
        }//void dormir
        public void cargar(int i){
            nproceso=(int) jTable1.getValueAt(i, 0);
            rafaga= parseInt((String) (jTable1.getValueAt(i, 1)));
            cantidad= parseInt((String)(jTable1.getValueAt(i, 2)));
            residuorafaga= parseInt((String) (jTable1.getValueAt(i, 3)));
            if(nproceso>0){
                lblnp.setText(String.valueOf(nproceso));
            }
        }//void cargar
        public void iniciar(){
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            txtpr.setVisible(false);
            txtcant.setVisible(false);
            btnadd.setVisible(false);
            btnstart.setVisible(false);
        }//void iniciar
        public void informe(int c){
            DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
            Object[] mitabla= new Object[5];
            mitabla[0]=c+1;
            mitabla[1]=rafaga;
            mitabla[2]=cantidad;
            mitabla[3]=tproceso+" segundos";
            mitabla[4]="Terminado";
            modelo2.addRow(mitabla);
            jTable2.setModel(modelo2);
            cantidadproceso++;
            lblcp.setText(String.valueOf(cantidadproceso+" Terminado"));
            lbltp.setText(String.valueOf(tproceso+" segundos"));
        }//void informe
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(procesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(procesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(procesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(procesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new procesar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblcp;
    private javax.swing.JLabel lblnp;
    private javax.swing.JLabel lblproc;
    private javax.swing.JLabel lbltp;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtpr;
    // End of variables declaration//GEN-END:variables
}
