/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arranque;

import formularios.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author AnToine
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        
        initComponents();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        setResizable(false);
        
        setIconImage (new ImageIcon(getClass().getResource("/images/icon.jpg")).getImage());
        foto();
        foto2();
        foto3();
        btnsalir();
        btnclien();
        btnrefa();
        btnsservicio();
        btnventa();
        MoveMouseListener mml = new MoveMouseListener(jLabel1);
        lblmover.addMouseListener(mml);
        lblmover.addMouseMotionListener(mml);
        float escalar = 0.5F; // una ventana al 50% del tamaño de la pantalla
int ancho = (int)(Toolkit.getDefaultToolkit().getScreenSize(). width*escalar);
int alto = (int)(Toolkit.getDefaultToolkit().getScreenSize(). height*escalar);
this.setSize(ancho,alto);
        
       // this.setExtendedState(MAXIMIZED_BOTH);
    }
public void foto(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/motos.jpg"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(300,300,Image.SCALE_SMOOTH));
        jLabel1.setIcon(iconoEscalado);
                     
}
public void foto2(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/max.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnmax.setIcon(iconoEscalado);
        if(btnmax.getText().equals("Maximizar" ) ) { 
setExtendedState( JFrame.MAXIMIZED_BOTH ) ; 
btnmax.setText("Restaurar"); 
lblmover.setEnabled(false);
}else{ 
setExtendedState( JFrame.NORMAL ) ; 
btnmax.setText( "Maximizar" ) ; 
lblmover.setEnabled(true);
} 
                     
}
public void foto3(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/move.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        lblmover.setIcon(iconoEscalado);
                     
}
public void btnsalir(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnsalir.setIcon(iconoEscalado);
                     
}
public void btnsservicio(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/servicio.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnservicio.setIcon(iconoEscalado);
                     
}
public void btnrefa(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/productos.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnrefacciones.setIcon(iconoEscalado);
                     
}
public void btnventa(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/venta.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnventa.setIcon(iconoEscalado);
                     
}
public void btnclien(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(50,50,Image.SCALE_SMOOTH));
        btnclientes.setIcon(iconoEscalado);
                     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblmover = new javax.swing.JLabel();
        btnmax = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnservicio = new javax.swing.JButton();
        btnrefacciones = new javax.swing.JButton();
        btnventa = new javax.swing.JButton();
        btnclientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBounds(new java.awt.Rectangle(50, 500, 100, 100));
        setName("index");
        setUndecorated(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicio.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel2.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 36)); // NOI18N
        jLabel2.setText("REFACCIONARIA de MOTOS");

        lblmover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/move.png"))); // NOI18N
        lblmover.setToolTipText("");
        lblmover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        btnmax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaxActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setToolTipText("Click para cerrar programa.");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnservicio.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        btnservicio.setText("Servicio");
        btnservicio.setToolTipText("Click para agregar, modificar, consultar o/y eliminar servicio");

        btnrefacciones.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        btnrefacciones.setText("Refacción");
        btnrefacciones.setToolTipText("Click para agregar, modificar, consultar o/y eliminar refacciones.");

        btnventa.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        btnventa.setText("Ventas");
        btnventa.setToolTipText("Click para agregar, consultar o/y eliminar venta.");

        btnclientes.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        btnclientes.setText("Clientes");
        btnclientes.setToolTipText("Click para agregar, modificar, consultar o/y eliminar clientes");
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmover, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrefacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnventa, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmover, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnventa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnrefacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaxActionPerformed
      if(btnmax.getText().equals("Maximizar" ) ) { 
setExtendedState( JFrame.MAXIMIZED_BOTH ) ; 
btnmax.setText("Restaurar"); 
lblmover.setEnabled(false);
}else{ 
setExtendedState( JFrame.NORMAL ) ; 
btnmax.setText( "Maximizar" ) ; 
lblmover.setEnabled(true);
} 

        // TODO add your handling code here:
    }//GEN-LAST:event_btnmaxActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
       /*clien ventana=new clien();
ventana.setLayout(null);
ventana.setSize(300,200);
ventana.setVisible(true);
ventana.setResizable(false);
ventana.setTitle("ejemplo");
ventana.setLocationRelativeTo(null);
* */
// TODO add your handling code here:
    }//GEN-LAST:event_btnclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btnmax;
    private javax.swing.JButton btnrefacciones;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnservicio;
    private javax.swing.JButton btnventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblmover;
    // End of variables declaration//GEN-END:variables
}
